language: java
env:
    global:
        - MAVEN_OPTS="-Xmx2g"
branches:
    only:
        - develop
        - master
install:
    - mvn anc:version
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
    - mvn clean
    - mvn compile
    - mvn test
